### ISSUE TITLE
The experience globs are not cumulating  when thrown far away and reset how much XP you will get

### ISSUE THREAD

**Issue by magrigry** [CodedRed-Spigot/XpBottles#4]
Experience globs not cumulating when thrown far away from the player. If you throw 64 bottle and then get the XP, you will only have xp like if you thorwn only 1 bottle

https://user-images.githubusercontent.com/74878280/119983726-d69a6200-bfc0-11eb-90d1-10a4cba4f17d.mp4

**Comment by CodedRedGIT** [comment]
Thanks for reporting, I've been looking into this and will come up with a solution very soon.

**Comment by CodedRedGIT** [comment]
Hello,

Thank you for your contribution by opening this issue a few years ago. At the time, the project had gone inactive which unfortunately led to your issue not being addressed. We apologize for any inconvenience caused.

We are excited to announce that we are resuming work on this project and in an effort to start fresh, we are going through the old issues to determine their current relevance.

As there has been a significant passage of time, we are closing out old issues. However, if you believe this issue is still relevant or if it hasn't been resolved, we warmly invite you to open a new issue with updated information. We appreciate your understanding and look forward to your continued support and contributions as we revive this project.

Thank you once again for your patience and involvement.

Best regards,
CodedRed
