### ISSUE TITLE
Suggestion for stack Xpbottle

### ISSUE THREAD

**Issue by DjeyMute** [CodedRed-Spigot/XpBottles#5]
Hi,

My players proposed to me to be able to add bottles of xp between them.
So that they become one.

**Comment by DjeyMute** [comment]
It's not the same, I just offer the plugin an improvement that allows you to automatically stack the bottles.
If it is not possible too bad.

**Comment by CodedRedGIT** [comment]
Sorry for the wait, I am looking into a better stack solution for the next update.

**Comment by CodedRedGIT** [comment]
Hello,

Thank you for your contribution by opening this issue a few years ago. At the time, the project had gone inactive which unfortunately led to your issue not being addressed. We apologize for any inconvenience caused.

We are excited to announce that we are resuming work on this project and in an effort to start fresh, we are going through the old issues to determine their current relevance.

As there has been a significant passage of time, we are closing out old issues. However, if you believe this issue is still relevant or if it hasn't been resolved, we warmly invite you to open a new issue with updated information. We appreciate your understanding and look forward to your continued support and contributions as we revive this project.

Thank you once again for your patience and involvement.

Best regards,
CodedRed
